### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-16prn#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by ifeoluwah21** [comment]
![Screenshot (195)](https://user-images.githubusercontent.com/69403530/192910143-9834a198-4b2a-4af8-9a74-2d92f92e3df5.png)
